orca_ged_document:
    resource: "@OrcaGedBundle/Controller/DocumentController.php"
    type:     annotation

orca_tesseract:
    resource: "@OrcaTesseractBundle/Controller/"
    type:     annotation
    prefix:   /

orca_ged:
    resource: "@OrcaGedBundle/Controller/"
    type:     annotation
    prefix:   /

