<?php

namespace Orca\GedBundle\Repository;

/**
 * CreditCaseDDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditCaseDDRepository extends \Doctrine\ORM\EntityRepository
{
}
