<?php

namespace Orca\GedBundle\Repository;

/**
 * CreditCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditCaseRepository extends \Doctrine\ORM\EntityRepository
{
}
