<?php

namespace Orca\GedBundle\Repository;

/**
 * metadataddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metadataddRepository extends \Doctrine\ORM\EntityRepository
{
}
