<?php

namespace Orca\GedBundle\Repository;

/**
 * metadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metadataRepository extends \Doctrine\ORM\EntityRepository
{
}
