<?php

namespace Orca\TesseractBundle\Repository;

/**
 * DataEnityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataEnityRepository extends \Doctrine\ORM\EntityRepository
{
}
