<?php

namespace Orca\TesseractBundle\Repository;

/**
 * metadatadocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metadatadocRepository extends \Doctrine\ORM\EntityRepository
{
}
